spring:
  datasource:
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          show-sql: false
    flyway:
      enabled: true
