spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice-shop-database
    username: postgres
    password: 12345679
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http:/localhost:8761/eureka/
  flyway:
    user: postgres
    password: 12345679
    schemas: product-schemas
    url: jdbc:postgresql://localhost:5432/microservice-shop-database
    enabled: true
    locations: filesystem:D:/repos/trainee-repo-YD/migration-service/src/main/resources/migration
