spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: 12345679
    eureka:
      instance:
        prefer-ip-address: false
      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http:/localhost:8761/eureka/