spring:
    data:
        redis:
          port: 6379
          host: localhost
          database: 0
          lettuce:
            pool:
              max-active: 8
              max-idle: 8
              min-idle: 0
              max-wait: 60s
          connect-timeout: 60s
    cache:
        type: redis
        redis:
          time-to-live: 60
          cache-null-values: true
          use-key-prefix: false
    jpa:
        properties:
          hibernate:
            default_schema: product-schemas
      application:
        name: order-service
  cloud:
    config:
      import-check:
        enabled: false
      fail-fast: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservice-shop-database
    username: postgres
    password: 12345679
server:
  port: 8083
keycloak:
  port: http://localhost:8888
  endpoint: /realms/services-dev-realm/protocol/openid-connect/token
  client:
    secret: s3wcVNRzWt4SJfOJhVkwvted3VzoVYn5
eureka:
  instance:
    prefer-ip-address: false
    client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http:/localhost:8761/eureka/
