eureka:
  instance:
    prefer-ip-address: false
    client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http:/localhost:8761/eureka/
zuul:
  routes:
    order:
      path: /api/orders
      url: http://localhost:8081
    product-service:
      path: /api/product/
      service-id:  product-service
    inventory:
      path:
      url: